name: Fetch commits

on: [push]

permissions: read-all

jobs:
   fetch-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch commit details
        id: fetch_commits
        uses: actions/github-script@v6
        with:
          script: |
            const commitsUrl = `https://github.com/FrancescoPetrosino/TestWiki/pull/7/commits`;
            await fetch(commitsUrl, {
              headers: { Authorization: `token $GITHUB_TOKEN` }
              'Content-Type': 'application/json'
            }).then(res => {
              if (!res.ok) {
                throw new Error(`HTTP error! status: ${res.status}`);
              }
              else {
                console.log('Response:', res.json());
              }
              return res.json();
            });

      - name: Output commit details
        run: |
          echo "The last 10 commits are:"
          echo "${{ env.commit_details }}"
          echo "Commit details have been stored in the environment variable."
          echo "You can use it in subsequent steps or jobs."
        env:
          commit_details: ${{ env.commit_details }}
