name: Fetch commits

on: [push]

permissions: read-all

jobs:
   fetch-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch commit details
        id: fetch_commits
        uses: actions/github-script@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
           const commits = await github.rest.repos.listCommits({
             owner: context.repo.owner,
             repo: context.repo.repo
           });
         
           console.log('Commits:', commits.data);
           return commits.data.map(commit => ({
             message: commit.commit.message,
             author: commit.commit.author.name,
             url: commit.html_url
           }));

      - name: Output commit details
        run: |
          echo "The last 10 commits are:"
          echo "${{ env.commit_details }}"
          echo "Commit details have been stored in the environment variable."
          echo "You can use it in subsequent steps or jobs."
        env:
          commit_details: ${{ env.commit_details }}
